- name: Set the BIG-IP authentication realm name
  bigip_device_httpd:
    auth_name: "{{ item.auth_name }}"
    auth_pam_dashboard_timeout: "{{ item.auth_pam_dashboard_timeout}}"
    auth_pam_idle_timeout: "{{ item.auth_pam_idle_timeout }}"
    auth_pam_validate_ip: "{{ item.auth_pam_validate_ip }}"
    fast_cgi_timeout: "{{ item.fast_cgi_timeout: }}"
    hostname_lookup: "{{ item.hostname_lookup }}"
    log_level: "{{ item.log_level }}"
    max_clients: "{{ item.max_clients }}"
    redirect_http_to_https: "{{ item.redirect_http_to_https }}"
    ssl_cipher_suite: "{{ item.ssl_cipher_suite }}"
    ssl_port: "{{ item.ssl_port }}"
    ssl_protocols: "{{ item.ssl_protocols }}"
    server: "{{ F5_SERVER }}"
    server_port: "{{ F5_SERVER_PORT }}"
    user: "{{ F5_USER }}"
    password: "{{ F5_PASSWORD }}"
    validate_certs: "{{ F5_VALIDATE_CERTS }}"
 loop: "{{ bigip_device_httpd }}"
