- name: Create server "GTM_Server"
  bigip_gtm_server:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    datacenter: "{{ item.datacenter }}"
    server_type: "{{ item.server_type }}"
    link_discovery: "{{ item.link_discovery }}"
    virtual_server_discovery: "{{ item.virtual_server_discovery }}"
    devices: "{{ item.device }}"
    server: "{{ F5_SERVER }}"
    server_port: "{{ F5_SERVER_PORT }}"
    user: "{{ F5_USER }}"
    password: "{{ F5_PASSWORD }}"
    validate_certs: "{{ F5_VALIDATE_CERTS }}"
  loop: "{{ bigip_gtm_server }}"
