- name: Manages SNMP v2c communities  by Dylan
  bigip_snmp_community:
    community: "{{ item.community }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    version: "{{ item.version }}"
    access: "{{ item.access }}"
    ip_version: "{{ item.ip_version }}"
    source: "{{ item.source }}"
    oid: "{{ item.oid }}"
    server: "{{ F5_SERVER }}"
    server_port: "{{ F5_SERVER_PORT }}"
    user: "{{ F5_USER }}"
    password: "{{ F5_PASSWORD }}"
    validate_certs: "{{ F5_VALIDATE_CERTS }}"
  loop: "{{ bigip_snmp_community }}"
