---
bigip_selfip_1:
  - name: 10.10.10.252
    address: 10.10.10.252
    netmask: 255.255.255.0
    vlan: vlan_10
    allow_service: all
  - name: 20.20.20.252
    address: 20.20.20.252
    netmask: 255.255.255.0
    vlan: vlan_20
    allow_service: all
  - name: 192.168.0.1
    address: 192.168.0.1
    netmask: 255.255.255.0
    vlan: vlan_4094
    allow_service: all

bigip_selfip_2:
  - name: 10.10.10.253
    address: 10.10.10.253
    netmask: 255.255.255.0
    vlan: vlan_10
    allow_service: all
  - name: 20.20.20.253
    address: 20.20.20.253
    netmask: 255.255.255.0
    vlan: vlan_20
    allow_service: all
  - name: 192.168.0.2
    address: 192.168.0.2
    netmask: 255.255.255.0
    vlan: vlan_4094
    allow_service: all
