bigip_data_group:
  - name: class_test
    state: present
    type: address
    internal: yes
    records:
      - key: 0.0.0.0/32
        value: External_NAT
      - key: 10.10.10.10
        value: No_NAT
